/**
 * TypeORM entity — Cat entity.
 * Represents a row in the `cats` PostgreSQL table.
 * Seeded with 1000 rows so the DB-layer cache demo shows a
 * measurable latency gap between a real Postgres query (MISS) and
 * the Redis-cached result (HIT).
 */
import {
    Entity, PrimaryGeneratedColumn, Column
} from "typeorm"

/**
 * Cat entity — maps to the `cats` table used for the caching demo.
 * Kept intentionally simple so learners focus on caching, not ORM complexity.
 */
@Entity("cats")
export class Cat {
    /** Auto-incremented primary key assigned by Postgres. */
    @PrimaryGeneratedColumn()
        id: number

    /** Cat's display name, generated by Faker in the seed endpoint. */
    @Column()
        name: string

    /** Breed string (e.g. "Siamese", "Bengal"), also generated by Faker. */
    @Column()
        breed: string
}
